---
services:
  zot:
    image: ghcr.io/project-zot/zot:latest
    ports:
      - "9000:8080"
    volumes:
      - ./hack/tests/zot.config.json:/etc/zot/config.json:ro
      - zot-data:/tmp/zot
    command: ["serve", "/etc/zot/config.json"]

  tpa:
    build:
      context: .
      dockerfile: hack/tests/Containerfile.tpa
    ports:
      - "8080:8080"

  minio:
    image: "quay.io/minio/minio:latest"
    ports:
      - "9900:9000"
      - "9901:9001"  # Web UI
    command: ["server", "--console-address", ":9001", "/data"]
    environment:
      MINIO_ROOT_USER: minioAccessKey
      MINIO_ROOT_PASSWORD: minioSecretKey

  createbuckets:
    image: quay.io/minio/mc:latest
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set minio http://minio:9000 minioAccessKey minioSecretKey && \
        mc mb minio/sboms;
      "

volumes:
  zot-data:
